{% set name = "wurst" %}
{% set version = "0.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f686eb87d523ba12286cd455e2a4fb8996b4c816564987d59960e71a15c11bc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - wurst-cli = wurst.bin.wurst_cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - appdirs
    - constructive_geometries >=0.9.4
    - docopt
    - numpy
    - pandas
    - python >={{ python_min }}
    - python-json-logger
    - toolz
    - tqdm
    - wrapt

test:
  imports:
    - wurst
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - wurst-cli --help

about:
  home: https://github.com/polca/wurst
  summary: Wurst is a python package for linking and modifying industrial ecology models
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/polca/wurst

extra:
  recipe-maintainers:
    - m-rossi
