{% set name = "wurst" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d9ed80af62074a6d3dd2566984f0787f4c4630fccbe1e72f0a690c6085713c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - wurst-cli = wurst.bin.wurst_cli:main

requirements:
  host:
    - pip
    - python >=3.4
    - setuptools
  run:
    - appdirs
    - constructive_geometries
    - docopt
    - numpy
    - pandas
    - python >=3.4
    - python-json-logger
    - toolz
    - tqdm
    - wrapt

test:
  imports:
    - wurst
  requires:
    - pip
  commands:
    - pip check
    - wurst-cli --help

about:
  home: https://github.com/polca/wurst
  summary: Wurst is a python package for linking and modifying industrial ecology models
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/polca/wurst

extra:
  recipe-maintainers:
    - m-rossi
